### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aruncs31s**
i got trouble installing pdftotext ,i thought this might help

### CODE REVIEW

**Comment by makerj** [comment]
Thank you for your contribution!

**Comment by makerj** [comment]
Can you explain a bit more under what circumstances the issue occurred?

**Comment by aruncs31s** [comment]
when i was trying to install pdftotext i got an an error like "some library is missing" while compiling and when i googled it the missing library was poppler , may be i can reproduce this error tomarow and send you the out put of that error

**Comment by aruncs31s** [comment]
@makerj 
#include <poppler/cpp/poppler-document.h>                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             1 error generated.                                    error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1                                                          [end of output]                                                                                         note: This error originates from a subprocess, and is likely not a problem with pip.                        ERROR: Failed building wheel for pdftotext          Failed to build pdftotext                             ERROR: Could not build wheels for pdftotext, which is required to install pyproject.toml-based projects

**Pull request merged**
